# Generated by Django 5.2.4 on 2025-10-16 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="아이 이름")),
                ("birth_date", models.DateField(verbose_name="출생일")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "남아"), ("female", "여아")],
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="보호자",
                    ),
                ),
            ],
            options={
                "verbose_name": "아이",
                "verbose_name_plural": "아이들",
                "db_table": "children",
                "ordering": ["-created_at"],
            },
        ),
    ]
