# Generated by Django 5.2.4 on 2025-10-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaccinationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaccine_id", models.IntegerField(verbose_name="백신 ID")),
                (
                    "vaccine_name",
                    models.CharField(max_length=100, verbose_name="백신명"),
                ),
                ("disease", models.CharField(max_length=100, verbose_name="질병명")),
                ("dose_number", models.IntegerField(verbose_name="접종 차수")),
                (
                    "age_description",
                    models.CharField(max_length=50, verbose_name="권장 시기"),
                ),
                ("vaccination_date", models.DateField(verbose_name="접종 예정일")),
                ("notification_date", models.DateField(verbose_name="알림 날짜")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="접종 완료"),
                ),
                (
                    "completed_date",
                    models.DateField(blank=True, null=True, verbose_name="실제 접종일"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="필수 접종"),
                ),
                (
                    "is_annual",
                    models.BooleanField(default=False, verbose_name="매년 접종"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_schedules",
                        to="children.child",
                        verbose_name="아이",
                    ),
                ),
            ],
            options={
                "verbose_name": "예방접종 일정",
                "verbose_name_plural": "예방접종 일정",
                "db_table": "vaccination_schedules",
                "ordering": ["vaccination_date"],
            },
        ),
        migrations.CreateModel(
            name="VaccinationNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_date", models.DateField(verbose_name="알림 날짜")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("sent", "발송됨"),
                            ("read", "읽음"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="발송 시간"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="읽은 시간"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="vaccinations.vaccinationschedule",
                        verbose_name="일정",
                    ),
                ),
            ],
            options={
                "verbose_name": "예방접종 알림",
                "verbose_name_plural": "예방접종 알림",
                "db_table": "vaccination_notifications",
                "ordering": ["-notification_date"],
            },
        ),
        migrations.AddIndex(
            model_name="vaccinationschedule",
            index=models.Index(
                fields=["child", "vaccination_date"],
                name="vaccination_child_i_f88013_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vaccinationschedule",
            index=models.Index(
                fields=["notification_date"], name="vaccination_notific_a5cd98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaccinationnotification",
            index=models.Index(
                fields=["notification_date", "status"],
                name="vaccination_notific_bbacbd_idx",
            ),
        ),
    ]
